<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="BuscaRcm" targetNamespace="urn:com.example.switchyard:rcm-switchyard:1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="urn:com.example.switchyard:rcm-switchyard:1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="urn:com.example.switchyard:rcm-switchyard:1.0" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="urn:com.example.switchyard:rcm-switchyard:1.0">
  <xsd:element name="buscarRcm" type="tns:buscarRcm"/>
  <xsd:complexType name="buscarRcm">
    <xsd:sequence>
      <xsd:element minOccurs="0" name="string" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="buscarRcmResponse" type="tns:buscarRcmResponse"/>
  <xsd:complexType name="buscarRcmResponse">
    <xsd:sequence>
      <xsd:element minOccurs="0" name="string" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
  </wsdl:types>
  <wsdl:message name="buscarRcmResponse">
    <wsdl:part name="parameters" element="tns:buscarRcmResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="buscarRcm">
    <wsdl:part name="parameters" element="tns:buscarRcm">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="BuscaRcmPortType">
    <wsdl:operation name="buscarRcm">
      <wsdl:input name="buscarRcm" message="tns:buscarRcm">
    </wsdl:input>
      <wsdl:output name="buscarRcmResponse" message="tns:buscarRcmResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BuscaRcmSoapBinding" type="tns:BuscaRcmPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="buscarRcm">
      <soap:operation soapAction="buscarRcm" style="document"/>
      <wsdl:input name="buscarRcm">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="buscarRcmResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BuscaRcm">
    <wsdl:port name="BuscaRcmPort" binding="tns:BuscaRcmSoapBinding">
      <soap:address location="http://localhost:8080/rcm-switchyard/BuscaRcm"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
